### ISSUE TITLE
Edit of MaxItemsPerPage

### ISSUE THREAD

**Issue by Olum-hack** [deburau/AmazonVineExplorer#5]
Pleas add that line to "globals.js". That make it possible to edit the MaxItemsPerPage variable.

`SETTINGS_USERCONFIG_DEFINES.push({key: 'MaxItemsPerPage', type: 'number', min: 20, max: 1000, name: 'Maximum items per page', description: 'Maximum items that will show up one one page'});`

**Comment by deburau** [comment]
Incorporated in version 0.11.0
