### ISSUE TITLE
Update "[09.10.2024] - Version 0.10.9.0.1.deburau.18" prevents script from finding all new items

### ISSUE THREAD

**Issue by EvilSugarbunny** [deburau/AmazonVineExplorer#6]
Hiya!

Been using your script version for a bit now since the original has been abandoned and I think you've added some great features.
May I be your alpha/beta tester (my programming/coding skills are far from functional)?

As the title already indicates, I think the most recent update prevents the script from detecting all new incoming items mainly because it stops searching once it found "three consecutive pages without new products".
I have tested it over the last three days. There were somewhere between 40 and 55 pages worth of new items added over the course of an entire day. As you probably know (and annoyingly so), they don't just get added one after another, but some pop up randomly anywhere within the pile of other new things.
The problem now occurs when you check the database maybe at 6pm on a new day and once you're done going through everything, you mark all items as seen. Then you might come back around 10pm in case some more items were added (which seems to happen a lot now) and you see a few more have dropped, BUT if you were to go through the pages manually, you would find A LOT more new items further back.
I found one as far back as page 27 after I had gone through the process as described above.

So, I would suggest changing the value for pages scanned with no new products to something higher than 50 (but probably below 100) in order to really get all new items.

Hope this makes sense.

**Comment by deburau** [comment]
Maybe my explanation of the new feature was not sufficient. The old scanning is still present, i.e. scanning each and every page, cleaning up the database and then sleeping for 3 hours until the process starts over.
The new and additional scanning starts every 5 minutes, whether the normal scan runs or not. So increasing the threshold of pages without new items to a large number makes no sense for me.
And BTW, if you want to start a full scan before the 3 hours passed, you can open the developer tools of you browser, go to Application / Local storage and set the value for "AVE_BACKGROUND_SCAN_LAST_TIME" to 0.

![image](https://github.com/user-attachments/assets/09e3c076-5058-4adc-95f8-abdc322c48f5)
